version: "3.9"

services:
  # ===== Hadoop HDFS =====
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=genome_hadoop
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/data
    ports:
      - "9000:9000"
      - "9870:9870"
    networks:
      - genome_hadoop_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - CLUSTER_NAME=genome_hadoop
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./data:/data
    ports:
      - "9864:9864"
    networks:
      - genome_hadoop_net

  # ===== Spark =====
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    networks:
      - genome_hadoop_net

  spark-worker:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - genome_hadoop_net

  pyspark-notebook:
    image: jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan
    environment:
      - PYSPARK_PYTHON=python3
    depends_on:
      - spark-master
    networks:
      - genome_hadoop_net

  # ===== Kafka & Zookeeper =====
    # ===== Zookeeper =====
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - genome_hadoop_net

  # ===== Kafka =====
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - genome_hadoop_net

  # ===== Hive Metastore =====
  hive-metastore:
    image: bde2020/hive-metastore-postgresql:latest
    container_name: hive-metastore
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "9083:9083"
    networks:
      - genome_hadoop_net
    depends_on:
      - namenode

  # ===== HiveServer2 =====
  hive-server:
    image: bde2020/hive:latest
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - HIVE_CONF_hive_exec_scratchdir=/tmp/hive
      - HIVE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
      - namenode
    networks:
      - genome_hadoop_net
  metadata-sender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata_sender
    volumes:
      - ./data:/app/data   # mount folder CSV v√† test images
    networks:
      - genome_hadoop_net
    depends_on:
      - kafka


volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  genome_hadoop_net:
    driver: bridge
